# Generated by Django 4.2.5 on 2024-04-10 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrals', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
